### ISSUE TITLE
emoji handling

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/commons#2]
Would we like clients to handle emojis as actual emoji characters or as :emoji_codes:?

Clients can convert to emoji characters, convert to :emoji_codes:, or leave it alone.

This could happen when posting a message and/or when displaying a message.

Complexities:
- CLI clients can't always display actual emojis depending on the font they're using.  Even if they can, they can be very small
- Some people run system tools which convert :codes: to actual emojis as they type
- Some emojis are actually a sequence of several characters such as skintone modifiers.  For example [Male Singer]:(https://emojipedia.org/male-singer/)
> The Man Singer emoji is a sequence of the 👨 Man and 🎤 Microphone emojis. These are combined using a zero width joiner between each character and display as a single emoji on supported platforms.

Composite emojis are only supported in some places.  Android supports them but not always MacOS Desktop.

**Comment by cinnamon-bun** [comment]
[node-emoji](https://www.npmjs.com/package/node-emoji) can convert between actual emojis and `:codes:`.  It doesn't understand Male Singer (`:man_singer:`)

[emoijlib](https://www.npmjs.com/package/emojilib) has Male Singer but no functions for autoconverting :codes:.

[twemoji](https://www.npmjs.com/package/twemoji) looked promising but converts emoji characters to `<img>` tags, not `:codes:`.

Anyway, if we find a good library this might be a useful thing to put into [cabal-client](https://github.com/cabal-club/cabal-client)

**Comment by fenwick67** [comment]
@cinnamon-bun does node-emoji work with `:male-singer:` ?

**Comment by fenwick67** [comment]
I had some more thoughts to add here.

I worked on (but abandoned and deleted) a branch on cabal-clone that would take unicode or `:codes:` and then look up custom emoji, then replace it with an `<img>`. 

I couldn't find a library that satisfied me so I wrote my own parsing function. Largely because none of them let me provide my own map of characters for codes or vice-versa. One thing I stuggled with was finding emoji characters. A big "Eureka" was when I realized `lodash.toArray('👩🏽‍🦰👴🏻')` splits the string into display characters (`['👩🏽‍🦰','👴🏻']`) successfully, handling the messy unicode stuff for you, including skin tone modifiers and zero-width-joins, and it does it reasonably quickly. 

I threw together a jsperf notebook here: https://jsperf.com/emoji-parsing/1 . Looks like converting is comparable performance-wise in either direction.

The biggest struggle we will have supporting short codes in both directions (unicode->`:code:` and `:code:`->unicode) is coming up with canonical names for all >3000 emoji, including "man in suit levitating with medium-light skin tone".  I did find [this file](https://raw.githubusercontent.com/joypixels/emoji-toolkit/master/emoji.json) from JoyPixels (the EmojiOne people), which defines a preferred shortcode and shortcode aliases.

**Comment by fenwick67** [comment]
I put [neato-emoji-converter](https://github.com/fenwick67/neato-emoji-converter) together yesterday/today to cover most emoji conversion use-cases, while being faster than most. It can borrow `emoji-toolkit`s very complete list of shortcodes and unicode sequences, so it can cover literally every official emoji sequence out of the box.

The emoji set and replacer functions are totally configurable, so it can be used for basically any emoji strategy I can think of.

It doesn't have any sort of picker integration.

**Comment by cblgh** [comment]
@fenwick67 ohhhhhh wha this looks really cool, it could help make [cabal-cli](https://github.com/cabal-club/cabal-cli/) handle emoji way better than the hack i implemented!

would you mind adding a license to https://github.com/fenwick67/neato-emoji-converter?

**Comment by fenwick67** [comment]
LICENSE added 👍

**Comment by fenwick67** [comment]
Hey y'all, I made a PR into cabal-cli to replace unicode with shortcodes https://github.com/cabal-club/cabal-cli/pull/132 . Let me know your thoughts.

**Comment by cblgh** [comment]
@fenwick67 solved this super nicely!
